'use client'

import jsPDF from 'jspdf'
import { toastError, toastSuccess } from '@/lib/toast'
import type { CalculatorState } from '../types/calculator.types'
import type { CalculationResult } from '../types/results.types'
import { generateMethodsParagraph } from './citations'

interface ExportInput {
  state: CalculatorState
  result: CalculationResult
}

export function exportToPdf({ state, result }: ExportInput): void {
  try {
    generatePdf({ state, result })
    toastSuccess('PDF downloaded')
  } catch (err) {
    toastError(
      'Could not generate PDF',
      err instanceof Error ? err.message : 'Unexpected error.'
    )
  }
}

function generatePdf({ state, result }: ExportInput): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 48
  const contentWidth = pageWidth - margin * 2
  let y = margin

  const write = (text: string, opts: { size?: number; bold?: boolean; color?: number[]; gap?: number } = {}) => {
    const { size = 11, bold = false, color = [24, 24, 27], gap = 14 } = opts
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(color[0], color[1], color[2])
    const lines = doc.splitTextToSize(text, contentWidth)
    doc.text(lines, margin, y)
    y += lines.length * gap
  }

  const rule = (gap = 8) => {
    doc.setDrawColor(228, 228, 231)
    doc.line(margin, y, pageWidth - margin, y)
    y += gap
  }

  // Header
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageWidth, 90, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Sample Size Report', margin, 56)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by SampleCalc', margin, 74)
  y = 120

  // Big N
  write(result.label, { size: 11, color: [113, 113, 122], bold: true, gap: 18 })
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(44)
  doc.setTextColor(99, 102, 241)
  doc.text(result.finalN.toLocaleString(), margin, y)
  y += 32
  write(result.sublabel, { size: 10, color: [113, 113, 122], gap: 20 })

  rule(16)

  // Metrics
  write('Key metrics', { size: 12, bold: true, gap: 18 })
  result.metrics.forEach((m) => {
    write(`  ${m.label}: ${m.value}${m.unit ? m.unit : ''}`, { size: 10, gap: 14 })
  })
  y += 8
  rule(16)

  // Formula
  write('Formula & calculation steps', { size: 12, bold: true, gap: 18 })
  doc.setFont('courier', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(63, 63, 70)
  const formulaLines = result.formula.split('\n')
  formulaLines.forEach((line) => {
    const split = doc.splitTextToSize(line, contentWidth)
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage()
      y = margin
    }
    doc.text(split, margin, y)
    y += split.length * 11
  })
  y += 8
  rule(16)

  // Assumptions
  if (y > doc.internal.pageSize.getHeight() - 200) {
    doc.addPage()
    y = margin
  }
  write('Assumptions', { size: 12, bold: true, gap: 18 })
  result.assumptions.forEach(([k, v]) => {
    write(`  ${k}: ${v}`, { size: 10, gap: 13 })
  })
  y += 8
  rule(16)

  // Methods paragraph
  if (y > doc.internal.pageSize.getHeight() - 200) {
    doc.addPage()
    y = margin
  }
  write('Suggested methods text', { size: 12, bold: true, gap: 18 })
  write(generateMethodsParagraph({ state, result }), { size: 10, gap: 14 })

  // Footer disclaimer
  y = doc.internal.pageSize.getHeight() - 40
  write(
    'Results should be reviewed by a qualified biostatistician before submission to ethics committees or journals.',
    { size: 8, color: [161, 161, 170], gap: 10 }
  )

  const filename = `samplecalc-${state.design ?? 'study'}-${Date.now()}.pdf`
  doc.save(filename)
}
